name: Build image and push to Edgegap Registry

on:
  push:
    branches: [test-pipeline]

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  PROJECT: ${{ secrets.PROJECT }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the image
        run: docker build . --file Dockerfile --tag $REGISTRY/$PROJECT/unity-pong:latest
      - name: Login to Edgegap Registry
        run: docker login $REGISTRY -u $REGISTRY_USERNAME -p $REGISTRY_TOKEN
      - name: Tagging
        run: docker push $REGISTRY $REGISTRY/$PROJECT/unity-pong:latest 