name: Build image and push to Edgegap Registry

on:
  push:
    branches: [test-pipeline]

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  PROJECT: ${{ secrets.PROJECT }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
  IMAGE_TAG: v1.0.0
  IMAGE_NAME: unity-pong

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the image
        run: docker build . --file Dockerfile --tag $REGISTRY/$PROJECT/$IMAGE_NAME
      - name: Login to Edgegap Registry
        run: docker login $REGISTRY -u $REGISTRY_USERNAME -p $REGISTRY_TOKEN
      - name: Tagging the image to desired version
        run: docker build . --file Dockerfile --tag $REGISTRY/$PROJECT/$IMAGE_NAME:$IMAGE_TAG
      - name: Pushing to Edgegap Registry
        run: docker push $REGISTRY/$PROJECT/$IMAGE_NAME:$IMAGE_TAG
      - name: Tagging the image to latest
        run: docker build . --file Dockerfile --tag $REGISTRY/$PROJECT/$IMAGE_NAME:latest
      - name: Pushing latest to Edgegap Registry
        run: docker push $REGISTRY/$PROJECT/$IMAGE_NAME:latest
