name: Tagging version

on:
  push:
    branches: [feature-1]

env:
  IMAGE_TAG: v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read VERSION file
        id: current_version
        run: echo "::set-output name=version::$(cat VERSION)"

      - name: Bump version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.current_version.outputs.version }}'
          version-fragment: "feature"

      - name: Do something with your bumped release version
        run: echo ${{ steps.bump_version.outputs.next-version }} > version.txt

      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
