name: Tagging version

on:
  push:
    branches: [feature-1]

env:
  IMAGE_TAG: v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ env.IMAGE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
