name: Patch Tagging version

on:
  push:
    branches: [develop]

env:
  VERSION_FILE: VERSION
  VERSION_FRAGMENT: bug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read VERSION file
        id: current_version
        run: echo "::set-output name=version::$(cat $VERSION_FILE)"

      - name: Bump version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.current_version.outputs.version }}
          version-fragment: "${{ env.VERSION_FRAGMENT}}"

      - name: Updating version file content
        run: echo ${{ steps.bump_version.outputs.next-version }} > $VERSION_FILE

      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.next-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Bumped new Version
