name: Tagging version

on:
  push:
    branches: [develop]

env:
  IMAGE_TAG: v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Tagging version
        run: git tag $IMAGE_TAG
